on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: curl https://chaowenguoorg.github.io/version/version.py | python
        - uses: actions/setup-python@main
          with:
              python-version: ${{env.PY}}
        - run: python -m compileall -b .
        - shell: python 
          run: |
              import pathlib, os
              pathlib.Path(os.getenv('GITHUB_ENV')).write_text('VERSION=' + os.getenv('PY')[:3])
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              context: web
              tags: chaowenguo/aiohttp
              build-args: VERSION=${{env.VERSION}}
        - uses: docker/build-push-action@master
          with:
              push: true
              context: chat
              tags: chaowenguo/chat:aiohttp
              build-args: VERSION=${{env.VERSION}}
        - uses: docker/build-push-action@master
          with:
              push: true
              context: proxy
              tags: chaowenguo/proxy
              build-args: VERSION=${{env.VERSION}}
